# Generated by Django 5.0 on 2024-01-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
