# Generated by Django 5.0 on 2024-01-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0002_pannel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pannel',
            name='food',
        ),
    ]
