# Generated by Django 5.0 on 2024-01-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0003_remove_pannel_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sciol',
            options={'verbose_name': 'sciol', 'verbose_name_plural': 'sciols'},
        ),
        migrations.AlterModelOptions(
            name='sciolvalues',
            options={'verbose_name': 'sciol_value', 'verbose_name_plural': 'sciol values'},
        ),
        migrations.AlterField(
            model_name='sciolvalues',
            name='value',
            field=models.URLField(max_length=255, verbose_name='ادرس'),
        ),
    ]
