# Generated by Django 5.0 on 2024-01-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0004_alter_sciol_options_alter_sciolvalues_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannel',
            name='pannel_name',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='نام پنل'),
            preserve_default=False,
        ),
    ]
