# Generated by Django 5.0 on 2024-01-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'راه های ارتباطی با ما',
                'verbose_name_plural': 'راه های ارتباطی با ما',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل')),
                ('description', models.TextField(verbose_name='توضحات')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='محل شعبه')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
                'db_table': 'contact_us',
            },
        ),
    ]
