# Generated by Django 5.0 on 2024-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('landing_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره ثابت')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='fax')),
                ('body', models.TextField(verbose_name='متن')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'راه های ارتباطی با ما',
                'verbose_name_plural': 'راه های ارتباطی با ما',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
                'db_table': 'contact_us',
            },
        ),
    ]
