# Generated by Django 5.0 on 2024-01-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='be_answered',
            field=models.BooleanField(default=False, verbose_name='پاسخ به صورت پیامک به من اعلام شود'),
        ),
    ]
