# Generated by Django 5.0 on 2024-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactus_be_answered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='WaysofCommunication',
        ),
        migrations.AddField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_us/%Y/%M/%d', verbose_name='عکس'),
        ),
    ]
