# Generated by Django 5.0 on 2024-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
