# Generated by Django 5.0 on 2024-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='fax'),
        ),
    ]
