# Generated by Django 5.0 on 2024-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='درباره خودت'),
        ),
    ]
