# Generated by Django 5.0 on 2024-01-07 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress_nation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=150, verbose_name='نام شغل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شغل',
                'verbose_name_plural': 'شغل ها',
                'db_table': 'job',
            },
        ),
    ]
