# Generated by Django 5.0 on 2024-01-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('code', models.PositiveSmallIntegerField(default=0)),
                ('create_code', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کد تایید',
                'db_table': 'otp_code',
            },
        ),
    ]
