# Generated by Django 5.0 on 2024-01-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
    ]
