# Generated by Django 5.0 on 2024-01-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
