# Generated by Django 5.0 on 2024-01-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان ادرس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=11, unique=True, verbose_name='کد پستی')),
                ('mobile_phone', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='ادرس کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
                'db_table': 'user_address',
            },
        ),
    ]
