# Generated by Django 5.0 on 2024-01-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
