# Generated by Django 5.0 on 2023-12-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('food_name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('food_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد غذاهای موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_get_out', models.BooleanField(default=True, verbose_name='بیرون بر')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_images', to='images.images')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('buy_price', models.PositiveIntegerField(default=0, verbose_name='قیمت خرید')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='قیمت فروش')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_price', to='food.food')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
                'db_table': 'food_price',
            },
        ),
    ]
