# Generated by Django 5.0 on 2024-01-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('images', '0001_initial'),
        ('pannel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('food_name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('food_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد غذاهای موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_get_out', models.BooleanField(default=True, verbose_name='بیرون بر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح در مورد غذا')),
                ('is_avaliable', models.BooleanField(default=True, verbose_name='غذا موجود هست')),
                ('buy_price', models.PositiveIntegerField(default=0, verbose_name='قیمت خرید')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='قیمت فروش')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_food', to='category.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_images', to='images.images')),
                ('pannel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannel_food', to='pannel.pannel')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'db_table': 'food',
            },
        ),
    ]
