# Generated by Django 5.0 on 2024-01-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('pannel', '0002_pannel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pannel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannel_food', to='pannel.pannel'),
        ),
    ]
