# Generated by Django 5.0 on 2024-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
