# Generated by Django 5.0 on 2024-01-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_pannel'),
        ('pannel', '0004_alter_sciol_options_alter_sciolvalues_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح در مورد غذا'),
        ),
        migrations.AddField(
            model_name='foodprice',
            name='pnnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannel_food_price', to='pannel.pannel', verbose_name='قیمت غذا'),
        ),
    ]
