# Generated by Django 5.0 on 2024-01-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح در مورد کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=True, verbose_name='کالا موجود هست'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_get_out',
            field=models.BooleanField(default=True, verbose_name='ارسال از طریق پست'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد کالاهای موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_category',
            field=models.CharField(blank=True, choices=[('featured', 'پیشنهاد شگفت\u200cانگیز'), ('popular', 'محبوب ترین'), ('discounted', 'تخفیفات ویژه'), ('Bestselling', 'پرفروش ترین')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductAtrribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('attribute_name', models.CharField(max_length=100, verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'db_table': 'product_attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='products.productatrribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='products.product')),
            ],
            options={
                'verbose_name': 'مقدار',
                'verbose_name_plural': 'مقدار ها',
                'db_table': 'product_attribute_value',
            },
        ),
    ]
