# Generated by Django 5.0 on 2024-01-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productatrribute',
            name='product',
        ),
    ]
