# Generated by Django 5.0 on 2024-01-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productatrribute_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productatrribute',
            name='attribute_value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_values', to='products.productattributevalue'),
            preserve_default=False,
        ),
    ]
