# Generated by Django 5.0 on 2024-01-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, max_length=100, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='برند'),
        ),
    ]
