# Generated by Django 5.0 on 2024-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_slug_alter_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام انگلیسی'),
        ),
    ]
